### ISSUE TITLE
requirement of pipestat

### ISSUE THREAD

**Issue by nsheff** [refgenie/refgenomes.databio.org#7]
this appears to now require a setup/configuration of pipestat but that is not specified in the readme

**Comment by nsheff** [comment]
probably good to put the actual pipestat config in this repo?

**Comment by nsheff** [comment]
Also I need a schema...but I have no idea what schema that should be. The schema should live with the pipeline (which in this case is just a pipeline interface)

**Comment by nsheff** [comment]
Do you think pipestat is actually even helpful here for these very short, interface-only pipelines? is it worth this added complexity? 

I mean, once it's set up properly it will be easier I know...

**Comment by stolarczyk** [comment]
you're right. I was experimenting with this in rg.databio.org repo and didn't realize the pipestat-related changes were included when copying over the files here...

I'll make it looper@master-compatible today

**Comment by nsheff** [comment]
actually I kind of like it. but it's not quite ready for primetime I guess. I am trying to set up a new refgenie instance (the bt2 one) and it's causing a few issues.

**Comment by stolarczyk** [comment]
yes, it will be useful; I think I got it to work with the `wget` pipeline interface and was able to monitor the status with `looper check --use-pipestat`

**Comment by nsheff** [comment]
So, monitoring is one thing, but the other advantage will be to be able to have looper be aware of which jobs are completed, right? That's not currently possible, I think.

This is the issue: https://github.com/pepkit/pipestat/issues/34

**Comment by stolarczyk** [comment]
That's what I meant by monitoring -- this way you can check which jobs completed and pipestat lets you do that. 

As I said, it worked with pipestat CLI in wget pipeline in this repo. This version of wget piface includes the `pipestat status` calls: https://github.com/refgenie/refgenomes.databio.org/blob/71fdbb9375148a141969a5b82820924f9b9ccfe3/pipeline_interfaces/wget_piface.yaml

Apart from that looper on dev uses pipestat Python API to get status in `looper check --use-pipestat`. I didn't put pipestat status management to pypiper yet, just played with it a couple of weeks ago. I need to revisit this, but I think it's going to work just fine.

**Comment by nsheff** [comment]
got it. This will be great. 

I was trying to make a distinction that it would also let you do `looper run` and it would only submit jobs that weren't already finished. That will be useful, too.
